export enum CommandEnum {
  START = 'START',
  GET_ACCESS = 'GET_ACCESS',
  QUESTION = 'QUESTION',
  FREE_TARIFF = 'FREE_TARIFF',
  DEVELOPER_TARIFF = 'DEVELOPER_TARIFF',
  UNLIMITED_TARIFF = 'UNLIMITED_TARIFF',
  JOIN_CHAT = 'JOIN_CHAT',
  CONFIRM_JOIN_CHAT = 'CONFIRM_JOIN_CHAT',
  GET_TOKEN = 'GET_TOKEN',
  GET_REQUEST_STATS = 'GET_REQUEST_STATS',
}
